# Generated by Django 2.1.4 on 2021-02-21 11:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190914_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 21, 11, 51, 38, 541011, tzinfo=utc), help_text='问题发布日期', verbose_name='date published'),
        ),
    ]
