# Generated by Django 2.1.4 on 2021-02-21 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210221_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='问题发布日期', verbose_name='date published'),
        ),
    ]
